// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDL_F7xkc8eER0fN3uwlNAJ742znojZYdA',
    appId: '1:736561562937:web:83e118e06d814ebb4494e8',
    messagingSenderId: '736561562937',
    projectId: 'huntermarket-f3270',
    authDomain: 'huntermarket-f3270.firebaseapp.com',
    storageBucket: 'huntermarket-f3270.firebasestorage.app',
    measurementId: 'G-4P2ZZE6SY0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCO7aDdOZdBSTWvZp7Iq1-WECTnEjtpXr0',
    appId: '1:736561562937:android:776d9f32083b8bcc4494e8',
    messagingSenderId: '736561562937',
    projectId: 'huntermarket-f3270',
    storageBucket: 'huntermarket-f3270.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyComqb2OJ9C1nVaIu9XsV3hLekprDvKum8',
    appId: '1:736561562937:ios:19bc958e136407b24494e8',
    messagingSenderId: '736561562937',
    projectId: 'huntermarket-f3270',
    storageBucket: 'huntermarket-f3270.firebasestorage.app',
    iosBundleId: 'com.example.cacaMilhas',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyComqb2OJ9C1nVaIu9XsV3hLekprDvKum8',
    appId: '1:736561562937:ios:19bc958e136407b24494e8',
    messagingSenderId: '736561562937',
    projectId: 'huntermarket-f3270',
    storageBucket: 'huntermarket-f3270.firebasestorage.app',
    iosBundleId: 'com.example.cacaMilhas',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDL_F7xkc8eER0fN3uwlNAJ742znojZYdA',
    appId: '1:736561562937:web:f418115d715177304494e8',
    messagingSenderId: '736561562937',
    projectId: 'huntermarket-f3270',
    authDomain: 'huntermarket-f3270.firebaseapp.com',
    storageBucket: 'huntermarket-f3270.firebasestorage.app',
    measurementId: 'G-LEFTJBQ4R6',
  );
}
